package aau.at.friendsifyfrontendservice.acceptanceTests;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.Disabled;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
@Disabled
public class AddFriendshipTest extends BaseLoggedInAcceptanceTest{
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Test
  public void addFriendship() {
//    driver.get("http://localhost:9000/friendsify/login");
//    driver.manage().window().setSize(new Dimension(1936, 1056));
//    driver.findElement(By.name("username")).click();
//    driver.findElement(By.name("username")).sendKeys("max@mustermann.de");
//    driver.findElement(By.name("password")).click();
//    driver.findElement(By.name("password")).sendKeys("password");
//    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Find new Friends")).click();
    driver.findElement(By.id("friends_new")).click();
    {
      WebElement dropdown = driver.findElement(By.id("friends_new"));
      dropdown.findElement(By.xpath("//option[. = 'Max Doe']")).click();
    }
    driver.findElement(By.cssSelector(".btn")).click();
    String url = driver.getCurrentUrl();
    driver.close();
    Assert.assertEquals("http://localhost:9000/friendsify/friends", url);
  }
}
