package aau.at.friendsifyfrontendservice.acceptanceTests;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;

import org.junit.jupiter.api.Disabled;
import org.openqa.selenium.By;

import org.openqa.selenium.WebElement;

@Disabled
public class AddFriendshipTest extends BaseLoggedInAcceptanceTest{

  @Test
  public void addFriendship() {
    super.setUp();

    super.getDriver().findElement(By.linkText("Find new Friends")).click();
    super.getDriver().findElement(By.id("friends_new")).click();
    {
      WebElement dropdown = super.getDriver().findElement(By.id("friends_new"));
      dropdown.findElement(By.xpath("//option[. = 'Max Doe']")).click();
    }
    super.getDriver().findElement(By.cssSelector(".btn")).click();
    String url = getDriver().getCurrentUrl();
    Assert.assertEquals("http://localhost:9000/friendsify/friends", url);
  }
}
