package aau.at.friendsifyfrontendservice.acceptanceTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import org.junit.jupiter.api.Disabled;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
@Disabled
public class AddPersonTest extends BaseLoggedInAcceptanceTest {
  JavascriptExecutor js;
  @Before
  public void setUp() {
    super.setUp();
    js = (JavascriptExecutor) super.getDriver();
  }

  @Test
  public void addPersonTest() {
    super.getDriver().findElement(By.linkText("Get started!")).click();

    List<WebElement> rows = super.getDriver().findElements(By.cssSelector("[class='table table-dark'] tr"));
    int size=rows.size();

    super.getDriver().findElement(By.id("firstName")).click();
    super.getDriver().findElement(By.id("firstName")).sendKeys("Anna");
    super.getDriver().findElement(By.id("lastName")).click();
    super.getDriver().findElement(By.id("lastName")).sendKeys("Mac");
    super.getDriver().findElement(By.id("email")).click();
    super.getDriver().findElement(By.id("email")).sendKeys("anna@mac.com");
    super.getDriver().findElement(By.id("birthdate")).click();
    super.getDriver().findElement(By.id("birthdate")).sendKeys("0002-06-08");
    super.getDriver().findElement(By.id("birthdate")).sendKeys("0020-06-08");
    super.getDriver().findElement(By.id("birthdate")).sendKeys("0200-06-08");
    super.getDriver().findElement(By.id("birthdate")).sendKeys("2000-06-08");
    super.getDriver().findElement(By.id("id_geoDB")).click();
    super.getDriver().findElement(By.id("id_geoDB")).sendKeys("Q41753");
    super.getDriver().findElement(By.id("city")).click();
    super.getDriver().findElement(By.id("city")).sendKeys("Klagenfurt");
    super.getDriver().findElement(By.id("password")).click();
    super.getDriver().findElement(By.id("password")).sendKeys("blacky");
    super.getDriver().findElement(By.id("repeated_password")).click();
    super.getDriver().findElement(By.id("repeated_password")).sendKeys("blacky");
    super.getDriver().findElement(By.cssSelector(".btn-primary")).click();

    rows = super.getDriver().findElements(By.cssSelector("[class='table table-dark'] tr"));

    assertEquals(size+1,rows.size());
  }
}
