# mvn install should be run before building the docker images!!

version: '3'

services:
  friendsify-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: placeholder # TODO: later replace with secret env variable 
      POSTGRES_USER: admin
      POSTGRES_DB: friendsify

  
  friendsify-person:
    image: friendsify-person
    build: friendsify-person-service
    ports:
      - "9001:9000"
    environment:
      - POSTGRES_DB=friendsify
      - POSTGRES_PASS=placeholder # TODO: later replace with secret env variable
    depends_on: 
      - friendsify-db
    restart: on-failure

  friendsify-email:
    image: friendsify-email
    build: friendsify-email-service
    ports: 
      - "9002:9000"
    environment:
      - POSTGRES_DB=friendsify
      - POSTGRES_PASS=placeholder # TODO: later replace with secret env variable
    depends_on:
      - friendsify-db
    restart: on-failure

  friendsify-friends:
    image: friendsify-friends
    build: friendsify-friends-service
    ports: 
     - "9003:9000"
    environment:
      - POSTGRES_DB=friendsify
      - POSTGRES_PASS=placeholder # TODO: later replace with secret env variable
    depends_on:
      - friendsify-person
      - friendsify-email
    restart: on-failure

  friendsify-joke:
   image: friendsify-joke
   build: friendsify-joke-service
   ports:
    - "9004:9000"
   environment:
     - POSTGRES_DB=friendsify
     - POSTGRES_PASS=placeholder # TODO: later replace with secret env variable
   depends_on:
     - friendsify-friends
   restart: on-failure

  friendsify-birthday:
    image: friendsify-birthday
    build: friendsify-birthday-service
    ports:
     - "9005:9000"
    environment:
      - POSTGRES_DB=friendsify
      - POSTGRES_PASS=placeholder # TODO: later replace with secret env variable
    depends_on:
      - friendsify-friends
    restart: on-failure

  friendsify-recommendations:
    image: friendsify-recommendations
    build: friendsify-recommendations-service
    ports:
     - "9006:9000"
    environment:
      - POSTGRES_DB=friendsify
      - POSTGRES_PASS=placeholder # TODO: later replace with secret env variable
    depends_on:
      - friendsify-friends
    restart: on-failure


  friendsify-frontend:
    image: friendsify-frontend
    build: friendsify-frontend-service
    ports: 
      - "9000:9000"
    depends_on:
      - friendsify-db
      - friendsify-person
      - friendsify-email
    restart: on-failure
