# mvn install should be run before building the docker images!!

version: '3'

services:
  person-db:
    image: postgres:alpine3.15
    restart: always
    volumes:
      - ./database/person/:/docker-entrypoint-initdb.d/
    ports:
      - 5001:5432
    environment:
     - POSTGRES_PASSWORD=placeholder # TODO: later replace with secret env variable
     - POSTGRES_USER=admin
     - POSTGRES_DB=friendsify

  friends-db:
    image: postgres:alpine3.15
    restart: always
    volumes:
      - ./database/friends/:/docker-entrypoint-initdb.d/
    ports:
      - 5002:5432
    environment:
      - POSTGRES_PASSWORD=placeholder # TODO: later replace with secret env variable
      - POSTGRES_USER=admin
      - POSTGRES_DB=friendsify

  friendsify-person:
    image: friendsify-person
    build: friendsify-person-service
    ports:
      - "9001:9001"
    environment:
      - POSTGRES_DB=friendsify
      - POSTGRES_PASS=placeholder # TODO: later replace with secret env variable
      - POSTGRES_USER=admin
      - DB_PORT=5001
    depends_on:
      - person-db
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"

  friendsify-email:
    image: friendsify-email
    build: friendsify-email-service
    ports:
      - "9002:9002"
    restart: on-failure

  friendsify-friends:
    image: friendsify-friends
    build: friendsify-friends-service
    ports: 
     - "9003:9003"
    environment:
      - POSTGRES_DB=friendsify
      - POSTGRES_PASS=placeholder # TODO: later replace with secret env variable
      - POSTGRES_USER=admin
      - DB_PORT=5002
    depends_on:
      - friends-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  friendsify-joke:
   image: friendsify-joke
   build: friendsify-joke-service
   ports:
    - "9004:9004"
   environment:
     - EMAIL_HOST=friendsify-email
     - EMAIL_PORT=9002
     - PERSON_HOST=friendsify-person
     - PERSON_PORT=9001
   env_file:
     - .env
   depends_on:
     - friendsify-person
     - friendsify-email
   restart: on-failure

  friendsify-birthday:
    image: friendsify-birthday
    build: friendsify-birthday-service
    ports:
     - "9005:9005"
    environment:
      - EMAIL_HOST=friendsify-email
      - EMAIL_PORT=9002
      - PERSON_HOST=friendsify-person
      - PERSON_PORT=9001
      - FRIENDS_HOST=friendsify-friends
      - FRIENDS_PORT=9003
    depends_on:
      - friendsify-person
      - friendsify-email
      - friendsify-friends
    restart: on-failure

  friendsify-recommendations:
    image: friendsify-recommendations
    build: friendsify-recommendations-service
    ports:
     - "9006:9006"
    environment:
       - PERSON_HOST=friendsify-person
       - PERSON_PORT=9001
       - FRIENDS_HOST=friendsify-friends
       - FRIENDS_PORT=9003
    depends_on:
       - friendsify-person
       - friendsify-friends
    restart: on-failure

  friendsify-weather:
    image: friendsify-weather
    build: friendsify-weather-service
    ports:
      - "9007:9007"
    env_file:
      - .env
    restart: on-failure

  friendsify-anniversary-reminder:
    image: friendsify-anniversary-reminder
    build: friendsify-anniversary-reminder-service
    ports:
      - "9008:9008"
    environment:
      - PERSON_HOST=friendsify-person
      - PERSON_PORT=9001
      - FRIENDS_HOST=friendsify-friends
      - FRIENDS_PORT=9003
    depends_on:
      - friendsify-person
      - friendsify-friends
    restart: on-failure


  friendsify-frontend:
    image: friendsify-frontend
    build: friendsify-frontend-service
    ports: 
      - "9000:9000"
    environment:
      - EMAIL_HOST=friendsify-email
      - EMAIL_PORT=9001
      - PERSON_HOST=friendsify-person
      - PERSON_PORT=9002
      - FRIENDS_HOST=friendsify-friends
      - FRIENDS_PORT=9003
      - JOKE_HOST=friendsify-joke
      - JOKE_PORT=9004
      - BIRTHDAY_HOST=friendsify-birthday
      - BIRTHDAY_PORT=9005
      - RECOMMENDATIONS_HOST=friendsify-recommendations
      - RECOMMENDATIONS_PORT=9006
      - WEATHER_HOST=friendsify-weather
      - WEATHER_PORT=9007
    restart: on-failure
