name: Performance-tests-JMeter
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run mvn install and skip tests
        run: mvn install -DskipTests
      - name: Run docker compose
        run: docker-compose -f docker-compose.yml up -d
      - name: check for service with curl
        run: curl http://${host.docker.internal}:9002/email
      - name: Run performance tests
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: friendsify-email-service/src/test/jmeter/performance-test.jmx
      - name: Stop docker compose
        run: docker-compose down
